spring:
  application:
    name: user-service

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

  datasource:
    url: jdbc:mysql://localhost:3307/user_service?serverTimezone=UTC
    username: root
    password: Urubu100
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  jackson:
    property-naming-strategy: SNAKE_CASE

  rabbitmq:
    host: localhost
    port: 5672
    username: dogfeliz
    password: Urubu100

url:
  name: "http://abrigodogfeliz.qzz.io:5173"

server:
  port: 7000
  error:
    include-stacktrace: never

aes:
  encryptor:
    secret-key: 7Fv9YkT8wHn2mQpLx3BzR0dKcW1uVnFhR2V4c0tZbW8=

security:
  hash:
    secret-key: 9xKf2LmQ7vT4sYpR8bWcZ3NqE1uD6HjA

  jwt:
    secret-key: w3JqVbYp6kK1xN8fTzQ2mH9cR4sD7uL5aE0pXyZbWcI=
    expiration-time: 1800000

  refresh-token:
    expiration-time: 3600000

mail:
  default-sender: gmail
  gmail:
    host: smtp.gmail.com
    port: 587
    username: gueirosdesouzav@gmail.com
    password: kedoxbxpdrziqafx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  outlook:
    host: smtp.office365.com
    port: 587
    username: lucas.eduardo.aiello@outlook.com
    password: usbsjufjcqcoblno
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cors:
  allowed-origins:
    - http://localhost:7000
    - http://localhost:5173
    - http://localhost:8000

  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS

notification:
  service:
    url: http://localhost:8000

melhor-envio:
  api:
    url: https://sandbox.melhorenvio.com.br
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI5NTYiLCJqdGkiOiJlN2VmOGY0M2UyMjVlYzAxYTE3MzA2NDZiYWY5YTRkNmVlYTVmODkyMzAyYmFhZGEyZGJjOTI3M2Y0NDFiMGMzNTA1MGUxOTQ4ZWMyYzEyMSIsImlhdCI6MTc2NTIwMDIwOC4yOTgzMDcsIm5iZiI6MTc2NTIwMDIwOC4yOTgzMSwiZXhwIjoxNzk2NzM2MjA4LjI5MDU2Mywic3ViIjoiYTA4YjQyOWYtNjQyMS00ZjQ0LTliZTItZGQ1MmEyN2NkZDgxIiwic2NvcGVzIjpbInNoaXBwaW5nLWNhbGN1bGF0ZSJdfQ.tP6qU07jTIDjjC2Y4tTlbzemt7daMRhSF-6R9QvLs3kRUcncg2HtIJOg_YOvE0-J8cjy44lzNRW5OvoQkepgkx5--YTM76lMlgLJy06Y6dVWTjESZkcMnYVYzg6cMkzCkDWnQfaNiMUYA2kCyvaFgw1ddhmEK6W9vWCHnu7FW6HLELOGhLcWWDpRnCQwl1GGO2K7bKVqMQIFCC3487rmNhfNDtAYiQBaVA2rXcQiFncKS3TyVfE3mRz7m79ZHxFgN261GkrDpyRQdohiFJfbrrAq9R-NXU_opZi5EJ-14mmCBVW3A2FG0cENb1c2y-Bw6MKwTSlEoTOrhkt02ewHs0ldXzqwHsz_Bjg17DDC3Kh3YEAJlkztG7wDk1BtMnOndriuvcsdGJdK6dAk33WuoAIu1-9Tf28eEuhX2poHTOIpexNPWTTFliTmbNG8a_bY94ugyJEciunsjtuL3g_MkfvhsGq9zKyDlDSpn9rMVSd-EbvQdTaymkdZlamdTn7gg7jly1YqE7IXCpfWngAGMYfOgwwz6NS7D4OcNMj2V7FPO7Wjl5UCjHuX6azVCdCVQO3KrS5mHbomkgHj5C63L_sRLZMGbBNvwrlcZX3y08nth3yGW6eSRDCZV346NmtdyqtZs52jRJ9-6st5yIMCVqKCjI2On6R7zlihz1Z5kEU
    user-agent: miguelito.angelo.sfc@gmail.com

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

uploads:
  path: uploads/fair/