#General
spring.application.name=user-service
server.port=7000

#Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#Jasypt
jasypt.encryptor.password=secret
jasypt.encryptor.fixed-salt=12345678

#Auth
security.jwt.secret-key=wO7CQZpv77s3n9j4OYtEjMLu3Ki5lQ0F1XkM7GfVo2o
security.jwt.expiration-time=360000