name: Backend CI (Reusable)

on:
  workflow_call:
    inputs:
      branch_type:
        description: "Which branch context is calling this workflow: dev or main"
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: false
      DOCKERHUB_TOKEN:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "maven"

      - name: Dar permissão ao Maven Wrapper
        run: chmod +x mvnw

      - name: Testes
        run: ./mvnw test

      - name: Buildar projeto (gera o JAR)
        run: ./mvnw -DskipTests clean package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Calcular short SHA
        id: vars
        run: echo "short_sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      # develop: só build local da imagem (valida Dockerfile), sem push
      - name: Build da imagem (sem push) - develop
        if: inputs.branch_type == 'dev'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: gustapa/user-service:dev-${{ steps.vars.outputs.short_sha }}

      # main: login + push latest + sha-curto
      - name: Login no Docker Hub - main
        if: inputs.branch_type == 'main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push - main
        if: inputs.branch_type == 'main'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            gustapa/user-service:latest
            gustapa/user-service:sha-${{ steps.vars.outputs.short_sha }}
