name: Backend CI

on:
  push:
    branches:
      - main
      - develop
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "maven"

      - name: Dar permissão ao Maven Wrapper
        run: chmod +x mvnw

      - name: Testes
        run: ./mvnw test

      - name: Buildar projeto (gera o JAR)
        run: ./mvnw -DskipTests clean package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # develop: só build local (valida Dockerfile + jar), não publica
      - name: Build da imagem (sem push) - develop
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: gustapa/user-service:dev-ci

      # main: login + push latest + sha
      - name: Login no Docker Hub - main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push - main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            gustapa/user-service:latest
            gustapa/user-service:${{ github.sha }}

      # release published: login + push tag do release + sha
      - name: Login no Docker Hub - release
        if: github.event_name == 'release'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push - release
        if: github.event_name == 'release'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            gustapa/user-service:${{ github.event.release.tag_name }}
            gustapa/user-service:${{ github.sha }}
