name: Backend CI - MAIN

on:
  push:
    branches:
      - main

jobs:
  backend-ci:
    uses: ./.github/workflows/backend-ci-reusable.yml
    with:
      branch_type: main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
